apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: apps
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      # IRSA (IAM Roles for Service Accounts) will be used for authentication
      # The service account needs to be annotated with the IAM role ARN
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: apps
  annotations:
    # Replace with the actual IAM role ARN created by Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-role

