apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: apps
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: apps

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-credentials
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: livekit-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LIVEKIT_URL: "{{ .LIVEKIT_URL }}"
        LIVEKIT_API_KEY: "{{ .LIVEKIT_API_KEY }}"
        LIVEKIT_API_SECRET: "{{ .LIVEKIT_API_SECRET }}"
  data:
    - secretKey: LIVEKIT_URL
      remoteRef:
        key: livekit-agent-secrets
        property: LIVEKIT_URL
    - secretKey: LIVEKIT_API_KEY
      remoteRef:
        key: livekit-agent-secrets
        property: LIVEKIT_API_KEY
    - secretKey: LIVEKIT_API_SECRET
      remoteRef:
        key: livekit-agent-secrets
        property: LIVEKIT_API_SECRET

