apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: apps
  annotations:
    # This will be set by the setup script or manually
    # Format: eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/CLUSTER_NAME-external-secrets-role
    eks.amazonaws.com/role-arn: REPLACE_WITH_EXTERNAL_SECRETS_IAM_ROLE_ARN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-operator
  namespace: apps
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-operator
  namespace: apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-secrets-operator
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: apps

